//
// Generated file, do not edit! Created by opp_msgc 4.5 from src/basetx100/hello.msg.
//

#ifndef _HELLO_M_H_
#define _HELLO_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0405
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif



/**
 * Class generated from <tt>src/basetx100/hello.msg</tt> by opp_msgc.
 * <pre>
 * packet Hello{
 *     int lpiClientID;
 * }
 * </pre>
 */
class Hello : public ::cPacket
{
  protected:
    int lpiClientID_var;

  private:
    void copy(const Hello& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Hello&);

  public:
    Hello(const char *name=NULL, int kind=0);
    Hello(const Hello& other);
    virtual ~Hello();
    Hello& operator=(const Hello& other);
    virtual Hello *dup() const {return new Hello(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getLpiClientID() const;
    virtual void setLpiClientID(int lpiClientID);
};

inline void doPacking(cCommBuffer *b, Hello& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, Hello& obj) {obj.parsimUnpack(b);}


#endif // _HELLO_M_H_
